name: Publish Zuki to NPM

on:
  push:
    tags:
      - 'v*' # S'exécute uniquement si le tag commence par "v", ex: v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'react/pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./react

      - name: Build Library
        run: pnpm run build:lib
        working-directory: ./react

      - name: Publish to NPM
        run: pnpm publish --access public
        working-directory: ./react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
